apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel
  namespace: laravel
  labels:
    app: laravel
spec:
  selector:
    matchLabels:
      app: laravel
  template:
    metadata:
      labels:
        app: laravel
    spec:
      containers:
      - name: laravel
        image: bitnami/laravel:11.0.8
        ports:
          - containerPort: 8000
        env:
          - name: LARAVEL_PORT_NUMBER
            value: "8000"
          - name: LARAVEL_SKIP_COMPOSER_UPDATE
            value: "no"
          - name: LARAVEL_SKIP_DATABASE
            value: "no"
          - name: LARAVEL_DATABASE_TYPE
            value: "mysql"
          - name: LARAVEL_DATABASE_HOST
            value: "db-svc"
          - name: LARAVEL_DATABASE_PORT_NUMBER
            value: "3306"
          - name: LARAVEL_DATABASE_NAME
            value: "laravel"
          - name: LARAVEL_DATABASE_USER
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: user
          - name: LARAVEL_DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: password
---

apiVersion: v1
kind: Service
metadata:
  name: laravel-svc
  namespace: laravel
spec:
  selector:
    app: laravel
  ports:
  - port: 8000
    targetPort: 8000
  type: NodePort
