apiVersion: v1
kind: LimitRange
metadata:
  name: resource-range-laravel
  namespace: laravel
spec:
  limits:
    - default:
        cpu: 200m
        memory: 870Mi
      max:
        cpu: 400m
        memory: 870Mi
      min:
        cpu: 200m
        memory: 512Mi
      type: Container
---
apiVersion: v1
kind: LimitRange
metadata:
  name: resource-range-phpmyadmin
  namespace: phpmyadmin
spec:
  limits:
    - default:
        cpu: 200m
        memory: 512Mi
      max:
        cpu: 400m
        memory: 870Mi
      min:
        cpu: 200m
        memory: 512Mi
      type: Container